### ISSUE TITLE
Plan for systematic review (current master)

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#296]
Once a chapter has been reviewed and corrected, it can be checked off.

Here, we focus on following goals:

1. is text **correct** and **up to date**
2. **shorten** text, remove historical references to Fluid, Neos, Pibase etc, **if** they are not relevant and helpful for learning extension development and only result in bloating up the text. The text is currently quite long and partly not well readable.
3. correct **language** (grammar, spelling, style), correct some phrases (that probably suffered during translation) and are really difficult to understand (e.g. [Programming Secure extensions](https://docs.typo3.org/m/typo3/book-extbasefluid/master/en-us/9-CrosscuttingConcerns/3-programming-secure-extensions.html))

### correct, up to date

for master (10-dev) - July 21, 2019

* [x] about
* [x] introduction
* [x] [basic design principles](https://docs.typo3.org/m/typo3/book-extbasefluid/master/en-us/2-BasicPrinciples/Index.html) - not TYPO3 version specific, should be basically ok
* [ ] [journey blog example](https://docs.typo3.org/m/typo3/book-extbasefluid/master/en-us/3-BlogExample/Index.html)
* [x] installation
* [ ] [creating a first extension](https://docs.typo3.org/m/typo3/book-extbasefluid/master/en-us/4-FirstExtension/Index.html) (see #231)
* [ ] [modeling the domain](https://docs.typo3.org/m/typo3/book-extbasefluid/master/en-us/5-Domain/Index.html)
* [ ] [persistence layer](https://docs.typo3.org/m/typo3/book-extbasefluid/master/en-us/6-Persistence/Index.html)
* [ ] [controlling the flow with controllers](https://docs.typo3.org/m/typo3/book-extbasefluid/master/en-us/7-Controllers/Index.html)
* [ ] [styling the output with fluid](https://docs.typo3.org/m/typo3/book-extbasefluid/master/en-us/8-Fluid/Index.html)
* [x] configuration (was just added)
* [ ]  internationalization
   * [ ] localization
   * [ ] validating domain objects
   * [ ] Programming secure extensions
   * [ ] Conclusion
* [x] backend modules
* [x] command controllers
* [ ]  property mapper
* [x] error action (was just added)
* [ ]  coding guidelines
* [ ]  extbase reference

### shorten text (remove redundancies)

for master (10-dev) - July 21, 2019

* [x] about
* [x] introduction
* [ ] basic design principles
* [ ] journey blog example
* [x] installation
* [ ] creating a first extension
* [ ] modeling the domain
* [ ] persistence layer
* [ ] controlling the flow with controllers
* [ ] [styling the output with fluid](https://docs.typo3.org/m/typo3/book-extbasefluid/master/en-us/8-Fluid/Index.html)
* [x] configuration (was just added)
* [ ]  internationalization
   * [ ] localization
   * [ ] validating domain objects
   * [x] Programming secure extensions (in progress ... #296)
   * [ ] Conclusion
* [x] backend modules
* [x] command controllers
* [ ]  property mapper
* [x] error action (was just added)
* [ ]  coding guidelines
* [ ]  extbase reference

### fix language (spelling, grammar, style), make more readable

for master (10-dev) - July 21, 2019

* [x] about
* [x] introduction
* [ ] basic design principles
* [ ] journey blog example
* [x] installation
* [ ] creating a first extension
* [ ] modeling the domain
* [ ] persistence layer
* [ ] controlling the flow with controllers
* [ ] [styling the output with fluid](https://docs.typo3.org/m/typo3/book-extbasefluid/master/en-us/8-Fluid/Index.html)
* [x] configuration (was just added)
* [ ]  internationalization
   * [ ] localization
   * [ ] validating domain objects
   * [x] Programming secure extensions (#296)
   * [ ] Conclusion
* [x] backend modules
* [x] command controllers
* [ ]  property mapper
* [x] error action (was just added)
* [ ]  coding guidelines
* [ ]  extbase reference

**Comment by sypets** [comment]
I am closing this now because:

* there are issues adressing the structure and further work reviewing does not make sense before that is handled IMHO.
